FROM python:3.9.25-slim

WORKDIR /app

COPY deployment/requirements.txt .
RUN pip install  -r requirements.txt

COPY common/ /app/common/
COPY deployment/ /app/deployment/

CMD ["python", "deployment/batch_predict.py"]