name: CD

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest -q
    
  build:
      needs: test
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Build Docker image
          run: |
            cd review
            docker build -t review-app:latest .
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy container
        run: |
         echo "Starting app in Docker..."
         docker run --rm -d -p 8000:8000 review-app:latest

